version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip
      - python -m pip install . --group docs
