from concurrent.futures import ThreadPoolExecutor, TimeoutError
from simopt.experiment_base import (
    PlotType,
    ProblemSolver,
    plot_progress_curves,
    post_normalize,
)


def main():
    experiments = [
        ["ADAM", "AMUSEMENTPARK-1"],
        ["ADAM", "CHESS-1"],
        ["ADAM", "CNTNEWS-1"],
        ["ADAM", "CONTAM-2"],
        ["ADAM", "CONTAM-1"],
        ["ADAM", "DUALSOURCING-1"],
        ["ADAM", "DYNAMNEWS-1"],
        ["ADAM", "EXAMPLE-1"],
        ["ADAM", "FACSIZE-2"],
        ["ADAM", "FACSIZE-1"],
        ["ADAM", "FIXEDSAN-1"],
        ["ADAM", "HOTEL-1"],
        ["ADAM", "IRONORE-1"],
        ["ADAM", "IRONORECONT-1"],
        ["ADAM", "MM1-1"],
        ["ADAM", "NETWORK-1"],
        ["ADAM", "PARAMESTI-1"],
        ["ADAM", "RMITD-1"],
        ["ADAM", "SAN-1"],
        ["ADAM", "SSCONT-1"],
        ["ADAM", "TABLEALLOCATION-1"],
        ["ALOE", "AMUSEMENTPARK-1"],
        ["ALOE", "CHESS-1"],
        ["ALOE", "CNTNEWS-1"],
        ["ALOE", "CONTAM-2"],
        ["ALOE", "CONTAM-1"],
        ["ALOE", "DUALSOURCING-1"],
        ["ALOE", "DYNAMNEWS-1"],
        ["ALOE", "EXAMPLE-1"],
        ["ALOE", "FACSIZE-2"],
        ["ALOE", "FACSIZE-1"],
        ["ALOE", "FIXEDSAN-1"],
        ["ALOE", "HOTEL-1"],
        ["ALOE", "IRONORE-1"],
        ["ALOE", "IRONORECONT-1"],
        ["ALOE", "MM1-1"],
        ["ALOE", "NETWORK-1"],
        ["ALOE", "PARAMESTI-1"],
        ["ALOE", "RMITD-1"],
        ["ALOE", "SAN-1"],
        ["ALOE", "SSCONT-1"],
        ["ALOE", "TABLEALLOCATION-1"],
        ["ASTRODF", "AMUSEMENTPARK-1"],
        ["ASTRODF", "CHESS-1"],
        ["ASTRODF", "CNTNEWS-1"],
        ["ASTRODF", "CONTAM-2"],
        ["ASTRODF", "CONTAM-1"],
        ["ASTRODF", "DUALSOURCING-1"],
        ["ASTRODF", "DYNAMNEWS-1"],
        ["ASTRODF", "EXAMPLE-1"],
        ["ASTRODF", "FACSIZE-2"],
        ["ASTRODF", "FACSIZE-1"],
        ["ASTRODF", "FIXEDSAN-1"],
        ["ASTRODF", "HOTEL-1"],
        ["ASTRODF", "IRONORE-1"],
        ["ASTRODF", "IRONORECONT-1"],
        ["ASTRODF", "MM1-1"],
        ["ASTRODF", "NETWORK-1"],
        ["ASTRODF", "PARAMESTI-1"],
        ["ASTRODF", "RMITD-1"],
        ["ASTRODF", "SAN-1"],
        ["ASTRODF", "SSCONT-1"],
        ["ASTRODF", "TABLEALLOCATION-1"],
        ["NELDMD", "AMUSEMENTPARK-1"],
        ["NELDMD", "CHESS-1"],
        ["NELDMD", "CNTNEWS-1"],
        ["NELDMD", "CONTAM-2"],
        ["NELDMD", "CONTAM-1"],
        ["NELDMD", "DUALSOURCING-1"],
        ["NELDMD", "DYNAMNEWS-1"],
        ["NELDMD", "EXAMPLE-1"],
        ["NELDMD", "FACSIZE-2"],
        ["NELDMD", "FACSIZE-1"],
        ["NELDMD", "FIXEDSAN-1"],
        ["NELDMD", "HOTEL-1"],
        ["NELDMD", "IRONORE-1"],
        ["NELDMD", "IRONORECONT-1"],
        ["NELDMD", "MM1-1"],
        ["NELDMD", "NETWORK-1"],
        ["NELDMD", "PARAMESTI-1"],
        ["NELDMD", "RMITD-1"],
        ["NELDMD", "SAN-1"],
        ["NELDMD", "SSCONT-1"],
        ["NELDMD", "TABLEALLOCATION-1"],
        ["RNDSRCH", "AMUSEMENTPARK-1"],
        ["RNDSRCH", "CHESS-1"],
        ["RNDSRCH", "CNTNEWS-1"],
        ["RNDSRCH", "CONTAM-2"],
        ["RNDSRCH", "CONTAM-1"],
        ["RNDSRCH", "DUALSOURCING-1"],
        ["RNDSRCH", "DYNAMNEWS-1"],
        ["RNDSRCH", "EXAMPLE-1"],
        ["RNDSRCH", "FACSIZE-2"],
        ["RNDSRCH", "FACSIZE-1"],
        ["RNDSRCH", "FIXEDSAN-1"],
        ["RNDSRCH", "HOTEL-1"],
        ["RNDSRCH", "IRONORE-1"],
        ["RNDSRCH", "IRONORECONT-1"],
        ["RNDSRCH", "MM1-1"],
        ["RNDSRCH", "NETWORK-1"],
        ["RNDSRCH", "PARAMESTI-1"],
        ["RNDSRCH", "RMITD-1"],
        ["RNDSRCH", "SAN-1"],
        ["RNDSRCH", "SSCONT-1"],
        ["RNDSRCH", "TABLEALLOCATION-1"],
        ["SPSA", "AMUSEMENTPARK-1"],
        ["SPSA", "CHESS-1"],
        ["SPSA", "CNTNEWS-1"],
        ["SPSA", "CONTAM-2"],
        ["SPSA", "CONTAM-1"],
        ["SPSA", "DUALSOURCING-1"],
        ["SPSA", "DYNAMNEWS-1"],
        ["SPSA", "EXAMPLE-1"],
        ["SPSA", "FACSIZE-2"],
        ["SPSA", "FACSIZE-1"],
        ["SPSA", "FIXEDSAN-1"],
        ["SPSA", "HOTEL-1"],
        ["SPSA", "IRONORE-1"],
        ["SPSA", "IRONORECONT-1"],
        ["SPSA", "MM1-1"],
        ["SPSA", "NETWORK-1"],
        ["SPSA", "PARAMESTI-1"],
        ["SPSA", "RMITD-1"],
        ["SPSA", "SAN-1"],
        ["SPSA", "SSCONT-1"],
        ["SPSA", "TABLEALLOCATION-1"],
        ["STRONG", "AMUSEMENTPARK-1"],
        ["STRONG", "CHESS-1"],
        ["STRONG", "CNTNEWS-1"],
        ["STRONG", "CONTAM-2"],
        ["STRONG", "CONTAM-1"],
        ["STRONG", "DUALSOURCING-1"],
        ["STRONG", "DYNAMNEWS-1"],
        ["STRONG", "EXAMPLE-1"],
        ["STRONG", "FACSIZE-2"],
        ["STRONG", "FACSIZE-1"],
        ["STRONG", "FIXEDSAN-1"],
        ["STRONG", "HOTEL-1"],
        ["STRONG", "IRONORE-1"],
        ["STRONG", "IRONORECONT-1"],
        ["STRONG", "MM1-1"],
        ["STRONG", "NETWORK-1"],
        ["STRONG", "PARAMESTI-1"],
        ["STRONG", "RMITD-1"],
        ["STRONG", "SAN-1"],
        ["STRONG", "SSCONT-1"],
        ["STRONG", "TABLEALLOCATION-1"],
    ]

    executor = ThreadPoolExecutor()

    def f(solver, problem):
        experiment = ProblemSolver(solver, problem)
        experiment.run(n_macroreps=1)
        experiment.post_replicate(n_postreps=1)
        post_normalize(experiments=[experiment], n_postreps_init_opt=1)

        experiment.log_experiment_results()
        plot_progress_curves(
            experiments=[experiment],
            plot_type=PlotType.MEAN,
            normalize=False,
        )

    for solver, problem in experiments:
        try:
            executor.submit(f, solver, problem).result(timeout=60)
        except TimeoutError:
            print(f"solver {solver}, problem {problem} timed out")
        except Exception as e:
            print(f"solver {solver}, problem {problem} failed due to {e}")
        finally:
            print(f"solver {solver}, problem {problem} done")


if __name__ == "__main__":
    main()
